SELECT
CASE
	WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'admin'
	THEN 'Administration'
	WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'education'
	THEN 'Education and Library'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'engineering'
    THEN 'Engineering and R&D'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'finance'
    THEN 'Finance'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'general management'
    THEN 'Senior and General Management'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'healthcare'
    THEN 'Medical and Healthcare'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'human resources'
    THEN 'Human Resources and Training'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'legal'
    THEN 'Legal'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'marketing'
    THEN 'Marketing'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'operations'
    THEN 'Operations'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'real estate'
    THEN 'Sales'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = NULL
    THEN 'Unclassified'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'research and development'
    THEN 'Engineering and R&D'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'sales'
    THEN 'Sales'
    WHEN TRIM(LOWER(REPLACE(ntw.b2b_job_function, '^', ''))) = 'technology'
    THEN 'Information Technology'
    ELSE 'Other'
END